fix updating packages: - fixes in get_pkg_version() - fixes in pkg_update():   * now versions retrieved from package names - fixes in get_pkg_name_only():   * prevents align-1.7.5 returning its name twice - pkg_update() now installs the new package, and its new deps - builtin packages cannot be updated:   * user gest a message saying the builtin will be skipped

diff --git a/usr/sbin/pkg b/usr/sbin/pkg
--- a/usr/sbin/pkg
+++ b/usr/sbin/pkg
@@ -314,6 +314,7 @@ get_pkg_version(){                # returns version of given package ($1) FUNCLI
 
   local pkg_ext=`get_pkg_ext "$1"`
   local PKGNAME=`get_pkg_name "$1"`
+  local PKGNAME_ONLY=`get_pkg_name_only "$PKGNAME"`
   
   # get $REPONAME and $EX 
   . ${PKGRC}
@@ -323,6 +324,7 @@ get_pkg_version(){                # returns version of given package ($1) FUNCLI
   case $pkg_ext in
     deb)
      DB_version="`echo "$PKGNAME" | cut -f 2 -d '_'`"
+     [ "$DB_version" = "$PKGNAME" ] && DB_version="`echo -n "$DB_version" | cut -f 2 -d '-'`"
      xDB_version="$DB_version"
     ;;
     pet)
@@ -345,7 +347,9 @@ get_pkg_version(){                # returns version of given package ($1) FUNCLI
     ;;
   esac
 
-  echo $xDB_version
+  version="${xDB_version//+*/}"
+  
+  echo $version | sed -e "s/^${PKGNAME_ONLY}-//g" -e "s/^${PKGNAME_ONLY}_//g" -e "s/^DEV-//g" -e "s/^DOC-//g" -e "s/^NLS-//g"
   return 0
 }
 
@@ -430,9 +434,11 @@ get_pkg_name_only(){              # return pkg name only, no version or suffix F
 
   # check the repos
   local pkg_name_only="`grep -m1 "|${1}|" ${HOME}/.packages/Packages-* | cut -f2 -d'|'`"
-  [ "$pkg_name_only" = '' ] && pkg_name_only="`grep -m1 "^${1}|" ${HOME}/.packages/Packages-* | cut -f2 -d'|'`"
-  [ "$pkg_name_only" = '' ] && pkg_name_only="`grep -m1 "|${1}.${pkg_ext}|" ${HOME}/.packages/Packages-* | cut -f2 -d'|'`"
+  [ "$pkg_name_only" = '' ] && pkg_name_only="`grep -m1 "^${1}|" ${HOME}/.packages/Packages-* | cut -f2 -d'|' | head -1`"
+  [ "$pkg_name_only" = '' ] && pkg_name_only="`grep -m1 "|${1}.${pkg_ext}|" ${HOME}/.packages/Packages-* | cut -f2 -d'|' | head -1`"
   
+  pkg_name_only=${pkg_name_only// */}
+
   # if we found it, print it and exit
   if [ "$pkg_name_only" != '' ];then
       echo ${pkg_name_only}
@@ -441,7 +447,8 @@ get_pkg_name_only(){              # return pkg name only, no version or suffix F
   
   # if not, but we have an extension, try  get_pkg_name_only_from_ext()
   case $DISTRO_BINARY_COMPAT in ubuntu|trisquel|debian|devuan)
-    name_only=`get_pkg_name_only_from_ext "$(basename "${1}.${repo_ext}")"`
+    name_only=`get_pkg_name_only_from_ext "$(basename "${1}.${repo_ext}")" | head -1`
+    name_only=${name_only// */}
     [ "$name_only" != '' -a "$name_only" != "$1" ] && echo $name_only && return 0
     ;;
   esac
@@ -4782,39 +4789,49 @@ pkg_update(){                    # update installed pets, if updates exist in re
     PKGNAME_ONLY=`get_pkg_name_only "$1"`
 
     # get installed packages
-    PKGLIST="`list_installed_pkgs "$PKGNAME_ONLY"`"
+    PKGLIST="`HIDE_BUILTINS=false list_installed_pkgs "$PKGNAME_ONLY"`"
 
-    is_builtin=`is_builtin_pkg "$PKGNAME"`
+    #is_builtin=`is_builtin_pkg "$PKGNAME"`
   
     # dont update builtins unless -F was given 
-    if [ "$is_builtin" = true -a "$HIDE_BUILTINS" = true ];then
-      echo -e "Package ${magenta}${PKGNAME}${endcolour} is built in, not updating."
-      #echo -e "Use `$SELF -F --pkg-update $PKGNAME` to update it anyway."
-      exit 0
-    fi
+    #if [ "$is_builtin" = true -a "$HIDE_BUILTINS" = true ];then
+    #  echo -e "Package ${magenta}${PKGNAME}${endcolour} is built in, not updating."
+    #  #echo -e "Use `$SELF -F --pkg-update $PKGNAME` to update it anyway."
+    #  exit 0
+    #fi
   else
     # get installed packages
-    PKGLIST="`list_installed_pkgs`"
+    PKGLIST="`HIDE_BUILTINS=false list_installed_pkgs`"
   fi
   
   # iterate over the list
-  echo "$PKGLIST"  | grep -v ^$ | sort | uniq | while read LINE; do
+  echo "$PKGLIST"  | grep -v ^$ | sort -u | while read LINE; do
 
     [ ! "$LINE" -o "$LINE" = '' ] && continue
     
     # if this pkg ($LINE) is not from a known repo, we cant compare its version to anything else, skip it
-    [ "`is_repo_pkg "$LINE"`" = false ] && echo -e "Package ${magenta}$LINE${endcolour} not found in any repos." && continue
+    #[ "`is_repo_pkg "$LINE"`" = false ] && echo -e "Package ${magenta}$LINE${endcolour} not found in any repos." && continue
     
-    PNAME='' PKGVER='' LATEST_PKG='' LATEST_PKGVER='' ASKREPLY='y'
+    PNAME='' PKGVER='' LATEST_REPO_PKG='' ASKREPLY='y'
     # get pkg name (without version) and version of current PKG
     
-    PNAME=`get_pkg_name_only "$LINE"`
-    pkg_ext=`get_pkg_ext "$PKGNAME"`
+    PNAME=`get_pkg_name_only $LINE`
+
+    case $DISTRO_BINARY_COMPAT in 
+      ubuntu|trisquel|debian|devuan)
+        [ "$LATEST_REPO_PKG" = '' ] && LATEST_REPO_PKG="`HIDE_BUILTINS=false list_all_pkg_names ${PNAME}_  | grep -m1 "^${PNAME}_"`"
+        [ "$LATEST_REPO_PKG" = '' ] && LATEST_REPO_PKG="`HIDE_BUILTINS=false list_installed_pkgs ${PNAME}_ | grep -m1 "^${PNAME}_"`"
+        [ "$LATEST_REPO_PKG" = '' ] && LATEST_REPO_PKG="`grep -m1 "$PNAME" ${HOME}/.packages/woof-installed-packages ${HOME}/.packages/layers-installed-packages |cut -f1 -d'|' | head -1 | cut -f2 -d':'`"
+      ;;
+      *)
+        [ "$LATEST_REPO_PKG" = '' ] && LATEST_REPO_PKG="`HIDE_BUILTINS=false list_all_pkg_names ${PNAME}-  | grep -m1 "^${PNAME}-"`"
+        [ "$LATEST_REPO_PKG" = '' ] && LATEST_REPO_PKG="`HIDE_BUILTINS=false list_installed_pkgs ${PNAME}- | grep -m1 "^${PNAME}-"`"
+        [ "$LATEST_REPO_PKG" = '' ] && LATEST_REPO_PKG="`grep -m1 "$PNAME" ${HOME}/.packages/woof-installed-packages ${HOME}/.packages/layers-installed-packages |cut -f1 -d'|' | head -1 | cut -f2 -d':'`"
+      ;;
+    esac
+
+    latest_version=`get_pkg_version "$LATEST_REPO_PKG"`
     installed_version=`get_pkg_version "$LINE"`
-
-
-    LATEST_PKG="`list_all_pkg_names "${PNAME}" | grep -m1 "^${PNAME}"`"
-    latest_version=`get_pkg_version "$LATEST_PKG"`
 
     # get latest versions
     
@@ -4832,23 +4849,21 @@ pkg_update(){                    # update installed pets, if updates exist in re
         fi
         
         if [ "$ASK" = false -o "$ASKREPLY" = "y" ];then
-          echo "Updating $PNAME to $latest_version"
-          #150813 dont involve deps, support --ask and --force
-          ASK=$ASK FORCE=$FORCE pkg_download "$LATEST_PKG"
-          # get the full name of the file we downloaded
-          PKGFILE="`list_downloaded_pkgs "$LATEST_PKG"`"
-          # now install it
-          [ "`is_local_pkg`" = true ] && ASK=$ASK FORCE=$FORCE pkg_install "$PKGFILE"
+          echo -e "${green}UPDATING${endcolour} $PNAME-${yellow}$installed_version${endcolour} to ${yellow}$latest_version${endcolour}"
+          cd "$WORKDIR"
+          ASK=$ASK FORCE=$FORCE pkg_get $LATEST_REPO_PKG
+          cd "$CURDIR"
         fi 
       
       else #280613 inform user if no update found
         echo "$PNAME-$installed_version (installed) is the latest available."
       fi #end if vercmp XX gt YY = 0
     
+    elif [ "$PNAME" = '' ];then
+      error "${LINE} not found."
     else #280613
-      error "Package versions could not be compared: 
-${latest_version:-unknown latest}, ${installed_version:-unknown installed version}"
-      exit 1
+      error "$LINE package versions could not be compared: ${latest_version:-unknown latest} => ${installed_version:-unknown installed version}"
+      #return 1
     fi #end if PKGVER != ""
   done
 }
@@ -6506,9 +6521,9 @@ while [ $# != 0 ]; do # get all options ($# means all options)
       --txz2pet|txz2pet) [ ! "$2" ] && txz2pet || for x in $opt; do txz2pet "$x"; done ;;
        
       # other
-      --func-list)    [ -f $TMPDIR/func_list ] && cat $TMPDIR/func_list || func_list; exit 0;;
-      --workdir)      [ "$2" != "-" ] && set_workdir "$2"; exit $?;;
-      --autoclean)    [ "$2" = "yes" -o "$2" = "no" ] && set_autoclean "$2" || { echo "$AUTOCLEAN"; exit 1; } ;;
+      --func-list|func-list)  [ -f $TMPDIR/func_list ] && cat $TMPDIR/func_list || func_list; exit 0;;
+      --workdir|workdir)      [ "$2" != "-" ] && set_workdir "$2"; exit $?;;
+      --autoclean|autoclean)  [ "$2" = "yes" -o "$2" = "no" ] && set_autoclean "$2" || { echo "$AUTOCLEAN"; exit 1; } ;;
       
       # usage, help funcs, version info, etc
       --welcome|welcome)          touch $HOME/.pkg/firstrun; first_run; exit 0;;
