added support for blacklisted packages: - get PKG_NAME_IGNORE from /root/.packages/PKGS_MANAGEMENT - skip/ignore pkgd and deps in various places if found in $PKG_NAME_IGNORE

diff --git a/usr/sbin/pkg b/usr/sbin/pkg
--- a/usr/sbin/pkg
+++ b/usr/sbin/pkg
@@ -115,6 +115,7 @@ fi
 [ -f /etc/rc.d/BOOTCONFIG ]               && . /etc/rc.d/BOOTCONFIG              #has EXTRASFSLIST PREVUNIONRECORD, LASTUNIONRECORD (sfs stuff)
 [ -f /etc/xdg/menus/hierarchy ]           && . /etc/xdg/menus/hierarchy          #w478 has PUPHIERARCHY variable.
 [ -f $HOME/.packages/DISTRO_PKGS_SPECS ]  && . $HOME/.packages/DISTRO_PKGS_SPECS #has lot sof essential info
+[ -f $HOME/.packages/PKGS_MANAGEMENT ]    && . $HOME/.packages/PKGS_MANAGEMENT   #has PKG_NAME_IGNORE, PKG_PET_THEN_BLACKLIST_COMPAT_KIDS, PKG_REPOS_ENABLED
 
 # set correct arch for repo URLs
 case "$DISTRO_TARGETARCH" in
@@ -517,6 +518,27 @@ get_pkg_name(){                   # return pkg name with version FUNCLIST
   [ "$full_name" = '' ] && echo "`basename "$pkg_name" .$pkg_ext`"
 }
 
+
+is_blacklisted_pkg(){             # return true if PKGNAME ($1) is blacklisted FUNCLIST
+  # exit if no valid options
+  [ ! "$1" -o "$1" = "-" ] && print_usage pkg-installed && exit 1
+  
+  local EX=''
+  local PKGNAME=''
+  local PKGNAME_ONLY=''
+  
+  # get pkg extension
+  EX=`get_pkg_ext "$1"`
+  
+  # strip away extension and path
+  PKGNAME="$(basename "$1" .$EX)"
+  #PKGNAME=`get_pkg_name "$PKGNAME"`
+  
+  # get the package name without version
+  PKGNAME_ONLY=`get_pkg_name_only "$PKGNAME"`
+  
+  [ "`echo "$PKG_NAME_IGNORE" | grep "$PKGNAME_ONLY "`" != '' ] && echo true || echo false
+}
 
 is_installed_pkg(){               # takes exact match of pkgname, prints true|false FUNCLIST
   
@@ -1436,6 +1458,23 @@ print_repo_info(){                # get repo settings, return current repo name 
 
 #pkg funcs
 
+hide_blacklisted_pkgs_from_search_results(){  # hide BUILTIN and installed pkgs from searches NOLIST
+
+  # dont hide package if using --force (the user may want to force a re-install of already installed pkg, for example)
+  [ "$FORCE" = true ] && return 0
+  
+  # get pkg names (generic names, no versions) of all blacklisted packages in pipe delimited list
+  blacklisted_pkgs_list="$(echo $PKG_NAME_IGNORE | sed -e 's/ /|/g')"
+    
+  # remove blacklisted packages from search list
+  cat $TMPDIR/pkglist | grep -v -E "'$blacklisted_pkgs_list'" > $TMPDIR/pkglist_without_blacklisted
+  mv $TMPDIR/pkglist_without_blacklisted $TMPDIR/pkglist
+  
+  # clean up tmp files
+  rm $TMPDIR/pkglist_* &>/dev/null
+}
+
+
 hide_installed_pkgs_from_search_results(){  # hide BUILTIN and installed pkgs from searches NOLIST
 
   # dont hide package if using --force (the user may want to force a re-install of already installed pkg, for example)
@@ -1477,6 +1516,8 @@ list_pkg_names(){                # list (matching) pkg names of current repo onl
   if [ $HIDE_INSTALLED = true ];then
     hide_installed_pkgs_from_search_results
   fi
+  
+  hide_blacklisted_pkgs_from_search_results
 
   # support pkg name aliases in finding packages
   if [ $NO_ALIASES = false ];then
@@ -1538,6 +1579,8 @@ list_all_pkg_names(){            # list (matching) pkg names of any repo FUNCLIS
   if [ $HIDE_INSTALLED = true ];then
     hide_installed_pkgs_from_search_results
   fi
+
+  hide_blacklisted_pkgs_from_search_results
 
   # support pkg name aliases in finding packages
   if [ $NO_ALIASES = false ];then
@@ -1656,6 +1699,8 @@ search_fast(){                   # current repo, show pkg names only, case sensi
     hide_installed_pkgs_from_search_results
   fi
 
+  hide_blacklisted_pkgs_from_search_results
+
   # now build the search results
   RES="`grep -v "^\$" $TMPDIR/pkglist 2>/dev/null | sort --field-separator='-' -k1,1df -k2gr -k3gr -k4gr | uniq`"
   rm $TMPDIR/pkglist &>/dev/null
@@ -1724,6 +1769,8 @@ search_all_fast(){               # all repos, show pkg names only, case sensitiv
     hide_installed_pkgs_from_search_results
   fi
   
+  hide_blacklisted_pkgs_from_search_results
+
   # now build the search results
   RES="`grep -v "^\$" $TMPDIR/pkglist 2>/dev/null | sort --field-separator='-' -k1,1df -k2gr -k3gr -k4gr | uniq`"
   rm $TMPDIR/pkglist &>/dev/null
@@ -3095,6 +3142,7 @@ pkg_install(){                   # install a downloaded package FUNCLIST
   [ "$PKGNAME" = '' ] && print_usage install && exit 1
 
   [ "`is_installed_pkg "$PKGNAME"`" = true -a "$FORCE" = false ] && echo "Already installed: $PKGNAME" && return 1
+  [ "`is_blacklisted_pkg "$PKGNAME_ONLY"`" = true ] && echo "Blacklisted package: $PKGNAME" && return 1
 
   if [ -f "$1" ];then
     PKGFILE="$1"
@@ -4072,12 +4120,12 @@ pkg_get(){                       # find, download and install packages and deps 
     [ "$pkg" = '' -o ! "$pkg" ] && continue
     
     local pkg_name=`get_pkg_name "$pkg" 2>/dev/null`
-
     [ "$pkg_name" = '' -o ! "$pkg_name" ] && continue
 
-    local pkg_name_only=`get_pkg_name_only "$pkg"`
+    local pkg_name_only=`get_pkg_name_only "$pkg" 2>/dev/null`
+    [ "`is_blacklisted_pkg "$pkg_name_only"`" = true ] && continue
+
     local pkg_already_done=`grep -m1 "^$pkg_name_only\$" $TMPDIR/PKGSDONE 2>/dev/null`
-    # dont install this package is if already in PKGSDONE
     [ "$pkg_already_done" != '' ] && continue
 
     local pkg_in_repo=`is_repo_pkg $pkg_name_only`
@@ -4224,7 +4272,7 @@ choose_pkg(){                    # choose from a list of matching packages FUNCL
     for LINE in `echo "$PKGS"  | sort -r` #first pkg found (newest) added to top, then the next, etc, sort use sort -r to keep newest at top of new list
     do
       # if not searching for -dev or -dgb pkg, move it to bottom of the list
-      if [ "`echo "$PKGNAME" | grep -E "\-dbg_|\-dev_"`" = "" -a "`echo "$LINE" | grep -E "\-dbg_|\-dev_"`" != "" ];then
+      if [ "`is_blacklisted_pkg "$LINE"`" = false -a "`echo "$PKGNAME" | grep -E "\-dbg_|\-dev_"`" = "" -a "`echo "$LINE" | grep -E "\-dbg_|\-dev_"`" != "" ];then
         PKGS="`echo "$PKGS" | grep -v  "$LINE"`" 
         PKGS="$PKGS
 $LINE"
@@ -4819,6 +4867,8 @@ list_deps(){                     # list all deps of PKG, space separated on one 
   PKGNAME=`get_pkg_name "$PKGNAME"`
   PKGNAME_ONLY=`get_pkg_name_only "$PKGNAME"`
 
+  blacklisted_pkgs_list="$(echo $PKG_NAME_IGNORE | sed -e 's/ /|/g')"
+  
   # create list of installed pkgs ($TMPDIR/installed_pkgs) for later
   list_all_installed_pkgs &
   
@@ -4842,7 +4892,7 @@ list_deps(){                     # list all deps of PKG, space separated on one 
 
     # remove any deps in installed pkgs list from all deps.. to leave only missing deps
     comm -23 ${TMPDIR}all_deps_0 ${TMPDIR}installed_pkgs | sort -u | grep -v ^$ > ${TMPDIR}all_deps_1
-
+    
     rm -f ${TMPDIR}DEP_DONE 2>/dev/null
     
     if [ -f $TMPDIR/all_deps_1 -a ! -z $TMPDIR/all_deps_1 ];then
@@ -4851,8 +4901,15 @@ list_deps(){                     # list all deps of PKG, space separated on one 
       do
         deps_list_file="${TMPDIR}all_deps_${i}"
         
+        
         if [ -f $deps_list_file ];then
+          
+          # remove all blacklisted packages from the list
+          cat "$deps_list_file" | grep -v -E "'$blacklisted_pkgs_list'" > ${TMPDIR}deps_list_file_without_blacklisted_pkgs
+          mv ${TMPDIR}deps_list_file_without_blacklisted_pkgs ${TMPDIR}deps_list_file
+
           next_deps_list_file="${TMPDIR}all_deps_$(($i + 1))"
+
           # for each dep in $deps, get their deps too
           for subdep in `cat $deps_list_file | sort -u | uniq | grep -v ^$`
           do
@@ -4869,9 +4926,11 @@ list_deps(){                     # list all deps of PKG, space separated on one 
 
             local is_builtin=`is_builtin_pkg "$subdep"`
             local is_in_devx=`is_devx_pkg "$subdep"`
+            local is_blacklisted=`is_blacklisted_pkg "$subdep"`
 
             [ "$HIDE_BUILTINS" = true -a "$is_builtin" = true ] && continue 
             [ "$HIDE_BUILTINS" = true -a "$is_in_devx" = true ] && continue 
+            [ "$is_blacklisted" = true ] && continue 
 
             subdeps_entry="`get_deps_entry "$subdep"`"
             subdeps="${subdeps_entry/+/}" # remove first + at start of line
@@ -4902,6 +4961,10 @@ list_deps(){                     # list all deps of PKG, space separated on one 
   if [ -f ${TMPDIR}installed_pkgs -a ! -z  ${TMPDIR}installed_pkgs ];then
     comm -23 ${TMPDIR}all_deps ${TMPDIR}installed_pkgs | sort -u | grep -v ^$ > ${TMPDIR}missing_deps
   fi
+
+  # remove all blacklisted packages from the list
+  cat ${TMPDIR}missing_deps | grep -v -E "'$blacklisted_pkgs_list'" > ${TMPDIR}missing_deps_without_blacklisted_pkgs
+  mv ${TMPDIR}missing_deps_without_blacklisted_pkgs ${TMPDIR}missing_deps
 
   [ ! -f ${TMPDIR}missing_deps -o -z ${TMPDIR}missing_deps ] && rm /tmp/pkg/list_deps_busy 2>/dev/null && return 1
   
@@ -5087,8 +5150,13 @@ get_deps(){                      # find, get and install the deps of pkg FUNCLIS
   local pkg_is_builtin=`is_builtin_pkg "$PKGNAME_ONLY" 2>/dev/null`
   local pkg_already_done=`LANG=C grep -m1 "^$PKGNAME_ONLY\$" $TMPDIR/PKGSDONE 2>/dev/null`
 
+  local pkg_is_blacklisted=`is_blacklisted_pkg "$PKG_NAME_ONLY" 2>/dev/null`
+  
   # if pkg is builtin, skip it, we dont need to get its dependencies
   [ "$pkg_is_builtin" = true -a "$HIDE_BUILTINS" = true ] && continue
+
+  # if pkg is blacklisted, also skip it
+  [ "$pkg_is_blacklisted" = true ] && continue
 
   # skip if already processed, it should be listed in $TMPDIR/PKGSDONE
   [ "$pkg_already_done" != "" -a "$FORCE" = false ] && continue 
@@ -5149,9 +5217,16 @@ get_deps(){                      # find, get and install the deps of pkg FUNCLIS
         local dep_already_done=`LANG=C grep -m1 "^$DEPNAME_ONLY\$" $TMPDIR/PKGSDONE 2>/dev/null`
         [ "$dep_already_done" != "" -a "$FORCE" = false ] && continue 
         
+        local dep_is_blacklisted=`is_blacklisted_pkg "$DEPNAME_ONLY" 2>/dev/null`
         local dep_is_builtin=`is_builtin_pkg "$DEPNAME_ONLY" 2>/dev/null`
         local dep_is_usr_pkg=`is_usr_pkg "$DEPNAME_ONLY" 2>/dev/null`
         local dep_is_in_devx=`is_devx_pkg "$DEPNAME_ONLY" 2>/dev/null`
+
+        # skip getting pkg if its blacklisted
+        if [ "$dep_is_blacklisted" = true ];then
+          echo "Skipping $DEPNAME_ONLY (blacklisted).."
+          continue
+        fi
 
         # skip getting pkg if its a builtin, unless HIDE_BUILTINS=false
         if [ "$dep_is_builtin" = true -a "${HIDE_BUILTINS}" = true ];then
@@ -6132,7 +6207,6 @@ first_run
 
 }
 #=====================  final checks  =======================#
-
 
 {
 #====================  main interface  ======================#
